codecov:
  bot: money-heist-hunter
  # token: ${{ secrets.CODECOV_TOKEN }}
  token: fbc0e6ae-3e0c-49ba-ab30-548a07a7feae
  require_ci_to_pass: yes
coverage:
  round: up
  precision: 2
  range: "70...100"
parsers:
  javascript:
    enable_partials: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  after_n_builds: 5
  branches:
    - "develop*"
