name: Linting with reviewdog

on:
  pull_request:
    branches:
      - development

jobs:
  eslint:
    name: check_eslint_error
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: eslint review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GH_TOKEN_API }}
          reporter: github-pr-check
          eslint_flags: "./**/*.{ts,js}"
